# Tensors

In [17]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [18]:
x = tf.constant("Hello")
x

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello'>

In [20]:
x = tf.Variable(123, tf.float64)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>

In [10]:
# TensorFlow 2.0, you don’t need to manually start a session to run the operations, unlike in TensorFlow 1.x. The operations are executed immediately.

In [11]:
rank_2_tensor = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float16)
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [12]:
a = tf.constant(3)
b = tf.constant(4)
a * b

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [15]:
# Placeholders no longer exist in 2.0

In [14]:
c = tf.placeholder(tf.float32)

AttributeError: module 'tensorflow' has no attribute 'placeholder'